# Compatible with podman-compose for improved security (rootless containers)
# Copy to parent directory of all applications /srv
services:
  # ========== POSTGRES DATABASE ==========
  authserver-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Reads from .env file
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  # Reads from .env file
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./authserver/database/init-security.sql:/docker-entrypoint-initdb.d/01-security.sql:ro
    ports:
      - "5432:5432"
    networks:
      aztech-network:
        aliases:
          - authserver-db
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
    security_opt:
      - no-new-privileges:true

  # ========== AUTH SERVER BACKEND ==========
  authserver-backend:
    image: localhost/srv_authserver-backend:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: authserver-db
      POSTGRES_EXTERNAL_PORT: 5432
      DISABLE_TLS: "true"
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      SESSION_AUTH_KEY: ${SESSION_AUTH_KEY}
      SESSION_ENCRYPTION_KEY: ${SESSION_ENCRYPTION_KEY}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      DOMAIN: ${DOMAIN}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      PORT: ${APP_PORT}
    ports:
      - "8080:8080"
    depends_on:
      authserver-db:
        condition: service_healthy
    networks:
      - aztech-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ========== AUTH SERVER FRONTEND ==========
  authserver-frontend:
    image: localhost/srv_authserver-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - aztech-network
    depends_on:
      authserver-backend:
        condition: service_healthy  # Changed from service_started
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# SINGLE networks section at the end
networks:
  aztech-network:
    external: true
    name: srv_aztech-network

# SINGLE volumes section at the end
volumes:
  postgres_data: