# Compatible with podman-compose for improved security (rootless containers)
# Copy to parent directory of all applications /srv
services:
  # ========== POSTGRES DATABASE ==========
  authserver-db:
    image: postgres:18 # Use official image for default installation
    container_name: authserver-db
    restart: unless-stopped
    environment: # Inline defaults instead of env_file for simplicity in testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql # this is the default data directory for postgres
      - ./authserver/database/init-security.sql:/docker-entrypoint-initdb.d/01-security.sql:ro
    ports:
      - 5432:5432
    networks:
      - aztech-network
    healthcheck:
      test: [
          CMD-SHELL,
          "pg_isready -U postgres -d postgres || exit 1", # Hardcode defaults to avoid variable issues
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    # Security hardening: Disable dangerous functions that could be exploited
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
    security_opt:
      - no-new-privileges:true

  # ========== CADDY PROXY ==========
  caddy:
    image: aztech-caddy:latest
    container_name: aztech-caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /srv/aztech-caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - aztech-network
    depends_on:
      # - django-landing-app
      - authserver-frontend
      - authserver-backend

  # ========== AUTH SERVER ==========
  authserver-backend:
    build: ./authserver/backend
    container_name: authserver-backend
    restart: unless-stopped
    env_file: ./authserver/backend/.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: authserver-db
      DISABLE_TLS: "true"
    depends_on:
      authserver-db:
        condition: service_healthy
    networks:
      - aztech-network

  authserver-frontend:
    build: ./authserver/frontend
    container_name: authserver-frontend
    restart: unless-stopped
    networks:
      - aztech-network

  # ========== DJANGO LANDING ==========
  # django-landing-app:
  #   image: django-landing-app
  #   container_name: django-landing-app
  #   restart: unless-stopped
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - aztech-network

  # django-landing-db:
  #   image: postgres:18
  #   container_name: django-landing-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${DJANGO_DB_NAME}
  #     POSTGRES_USER: ${DJANGO_DB_USER}
  #     POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
  #   volumes:
  #     - django_db_data:/var/lib/postgresql/data
  #   ports:
  #     - 5433:5432
  #   networks:
  #     - aztech-network

  # ========== PORTAINER ==========
  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #     - 9443:9443
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   networks:
  #     - aztech-network

  # ========== SECURITY SCANNING ==========
  # Optional security scanner - uncomment to enable vulnerability scanning
  # security-scanner:
  #   image: aquasecurity/trivy:latest
  #   container_name: security-scanner
  #   profiles: ["security"]
  #   command: >
  #     trivy image
  #     --format table
  #     --exit-code 1
  #     --ignore-unfixed
  #     --vuln-type os,library
  #     authserver-db:latest
  #     authserver-backend:latest
  #     authserver-frontend:latest
  #     aztech-caddy:latest
  #   volumes:
  #     - /tmp/trivy-cache:/root/.cache/trivy
  #   networks:
  #     - aztech-network

# SINGLE networks section at the end
networks:
  aztech-network:
    driver: bridge

# SINGLE volumes section at the end
volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  # django_db_data:
  # portainer_data:
